"""
Configuration constants for the Financial Crime Detection Engine.
All detection thresholds are centralized here for easy tuning.

Time Complexity: N/A (constants only)
Memory: O(1)
"""

# --- Cycle Detection ---
MIN_CYCLE_LENGTH = 3
MAX_CYCLE_LENGTH = 5
CYCLE_TIME_SPAN_HOURS = 72
CYCLE_AMOUNT_CV_THRESHOLD = 0.25

# --- Smurfing Detection ---
SMURFING_WINDOW_HOURS = 72
SMURFING_MIN_COUNTERPARTIES = 8
SMURFING_MEAN_AMOUNT_FACTOR = 5.0
SMURFING_FORWARD_RATIO_THRESHOLD = 0.7
SMURFING_FANOUT_CV_THRESHOLD = 0.3

# --- Shell Detection ---
SHELL_MAX_DEGREE = 3
SHELL_MAX_TRANSACTIONS = 3
SHELL_HOLDING_TIME_HOURS = 24
SHELL_MIN_CHAIN_LENGTH = 3

# --- High Velocity ---
HIGH_VELOCITY_THRESHOLD = 2.5
VELOCITY_WINDOW_HOURS = 72

# --- Scoring ---
SCORE_CYCLE = 90
SCORE_SMURFING_AGGREGATOR = 85
SCORE_SMURFING_DISPERSER = 25
SCORE_SHELL = 95
SCORE_HIGH_VELOCITY = 25
SCORE_MULTI_PATTERN_BONUS = 35
SCORE_MERCHANT_PENALTY = -40
SCORE_PAYROLL_PENALTY = -30

# --- Holding Time Analysis ---
HOLDING_TIME_THRESHOLD_HOURS = 2
HOLDING_FORWARD_RATIO = 0.8
SCORE_RAPID_PASS_THROUGH = 15

# --- Activity Spike Detection ---
SPIKE_MULTIPLIER = 5
SPIKE_MIN_TRANSACTIONS = 10
SCORE_ACTIVITY_SPIKE = 20

# --- Centrality Analysis ---
CENTRALITY_PERCENTILE = 95
SCORE_HIGH_CENTRALITY = 10

# --- Ring Density ---
RING_DENSITY_THRESHOLD = 0.5
RING_DENSITY_BONUS_PERCENT = 15

# --- Nonlinear Amplifier ---
NONLINEAR_BASE_BONUS = 20
NONLINEAR_PER_PATTERN = 5
NONLINEAR_MIN_PATTERNS = 3

# --- Retention Analysis ---
RETENTION_LOW = -0.1
RETENTION_HIGH = 0.1
SCORE_LOW_RETENTION = 25

# --- Flow Metrics ---
THROUGHPUT_LOW = 0.9
THROUGHPUT_HIGH = 1.1
SCORE_HIGH_THROUGHPUT = 20
SCORE_BALANCE_OSCILLATION = 20

# --- Diversity Analysis ---
SCORE_BURST_DIVERSITY = 20

# --- SCC Analysis ---
SCC_MIN_SIZE = 3
SCORE_LARGE_SCC = 10

# --- Cascade Depth ---
CASCADE_MAX_HOPS = 5
CASCADE_WINDOW_HOURS = 72
CASCADE_MIN_DEPTH = 3
SCORE_DEEP_CASCADE = 30

# --- Activity Consistency ---
SCORE_IRREGULAR_ACTIVITY = 20

# --- Risk Propagation ---
RISK_PROPAGATION_ALPHA = 0.25
RISK_PROPAGATION_ITERATIONS = 3

# --- Closeness Centrality ---
SCORE_HIGH_CLOSENESS = 10

# --- Clustering ---
SCORE_HIGH_CLUSTERING = 5

# --- False Positive ---
MERCHANT_MIN_COUNTERPARTIES = 50
MERCHANT_MIN_SPAN_DAYS = 90
PAYROLL_SIMILAR_AMOUNT_CV = 0.1
PAYROLL_MIN_MONTHS = 3

# --- Forwarding Latency ---
FORWARDING_LATENCY_MEDIAN_HOURS = 2
SCORE_RAPID_FORWARDING = 20

# --- Dormancy Analysis ---
DORMANCY_INACTIVE_DAYS = 30
DORMANCY_BURST_HOURS = 48
DORMANCY_MIN_BURST_TXNS = 5
SCORE_DORMANT_ACTIVATION = 60

# --- Amount Structuring ---
STRUCTURING_CV_THRESHOLD = 0.15
STRUCTURING_MIN_TXNS = 5
STRUCTURING_WINDOW_HOURS = 72
SCORE_STRUCTURED_FRAGMENTATION = 10

# --- ML Scoring ---
ML_MODEL_PATH = "core/ml/models/risk_model_v1.pkl"
# Keep the learned model slightly dominant, but retain rule evidence as a
# stabilizer so single-pattern noise does not overtake structural findings.
ML_RULE_WEIGHT = 0.45
ML_MODEL_WEIGHT = 0.55
ML_ENABLED = True
